server:
  port: 9095
spring:
  datasource:
    username: scott
    password: tiger
    url: jdbc:oracle:thin:@localhost:1521:ORCL
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create-drop
      hibernate:
        dialect: org.hibernate.dialect.11gDialect
  mvc:
    view:
      prefix: /views/
      suffix: .jsp

  mail:
    host: smtp.gmail.com
    port: 587
    username: 98dhirajgupta@gmail.com
    password: India/0109
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
      protocol: smtp
      test-connection: false
      
